### ISSUE TITLE
Strange Behaviour

### ISSUE THREAD

**Issue by ServusJon** [sujin2f/Hosts-File-Changer#1]
Hi! 
I just build it on the mac and edited my hostfile. Then I exported the file but I couldn't see an effect. The websites I wrote in the host file weren't blocked. What did I do wrong?

**Comment by sujin2f** [comment]
Hi ServusJon,

I think you could watch your hosts file and check out if it works fine.

Go to Terminal app, type <code>vim /etc/hosts</code>. If the change were submitted, it is because of cache. (I should update this part!) 

Check out here http://osxdaily.com/2014/11/20/flush-dns-cache-mac-os-x/

If the change were not submitted, it's my fault but I don't have no idea ;ㅁ;

Thanks.

**Comment by sujin2f** [comment]
Anyway, I have to update this code because there are so many unused menus... 'ㅅ'

**Comment by ServusJon** [comment]
Any plans on refactoring ;-)?

**Comment by sujin2f** [comment]
I will if I have enough time to do :)

This application is basically for my own need because I couldn't find any other application to change the hosts file - it may because of the policy of Apple - and I'm not a OSX developer :)

**Comment by ServusJon** [comment]
I am thinking about building a pornblocker and i want to add a big text file to the host file.
Not sure if this is a good approach. The textfile is over 15mb big

**Comment by sujin2f** [comment]
15Mb? +_+ God! I think this application will shut down....

**Comment by ServusJon** [comment]
yes, 15mb.
Its a txt file from a blacklist server ;-)
